when@test:
  framework:
    test: true
    session:
      enabled: true
      handler_id: null
      cookie_lifetime: 3600
      cookie_secure: auto
      cookie_samesite: lax

when@dev:
  framework:
    test: true
    session:
      enabled: true
      handler_id: null
      cookie_lifetime: 3600
      cookie_secure: auto
      cookie_samesite: lax