services:
  nginx:
    image: ${COMPOSE_PROJECT_NAME}-nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - php
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - "./:/var/${COMPOSE_PROJECT_NAME}"
    ports:
      - "${HOST_IP}:35080:80"
    networks:
      - spark-networks

  php:
    image: ${COMPOSE_PROJECT_NAME}-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      tags:
        - php-spark
    user: "${USERID}:${GROUPID}"
    volumes:
      - "./log:/var/${COMPOSE_PROJECT_NAME}/log"
      - "$PWD:/var/${COMPOSE_PROJECT_NAME}"
    working_dir: /var/${COMPOSE_PROJECT_NAME}
    networks:
      - spark-networks

networks:
  spark-networks:
    name: "${COMPOSE_PROJECT_NAME}-network"
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: fdff:1:1::/112
          gateway: fdff:1:1::1

