parameters:
  kernel.secret: '%env(APP_SECRET)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Spark\Web\Service\MlpService: ~
  Spark\Web\Service\TreeService: ~

  Spark\Web\Controller\:
    resource: '../src/Web/Controller'
    tags: ['controller.service_arguments']